- id: sync-mypy-additional-dependencies
  name: sync-mypy-additional-dependencies
  description: Sync dependencies between poetry groups and mypy pre-commit hook's additional_dependencies
  entry: sync-mypy-additional-dependencies
  language: python
  language_version: python3
  files: '^\.pre-commit-config.yaml$'
